from pathlib import WindowsPath, PosixPath
from falcor import *

def render_graph_Dither():
    g = RenderGraph('Dither')
    g.create_pass('VBufferLighting', 'VBufferLighting', {'envMapIntensity': 0.25, 'ambientIntensity': 0.25, 'lightIntensity': 0.5, 'envMapMirror': False})
    g.create_pass('DitherVBuffer', 'DitherVBuffer', {})
    g.create_pass('ToneMapper', 'ToneMapper', {'outputSize': 'Default', 'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': 'Linear', 'clamp': False, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': 'AperturePriority'})
    g.create_pass('TAA', 'TAA', {'alpha': 0.10000000149011612, 'colorBoxSigma': 1.0, 'antiFlicker': False})
    g.create_pass('DLSSPass', 'DLSSPass', {'enabled': True, 'outputSize': 'Default', 'profile': 'DLAA', 'preset': 'Default(CNN)', 'motionVectorScale': 'Relative', 'isHDR': True, 'useJitteredMV': False, 'sharpness': 0.3499999940395355, 'exposure': 0.0})
    g.create_pass('UnpackVBuffer', 'UnpackVBuffer', {})
    g.create_pass('RayShadow', 'RayShadow', {})
    g.create_pass('AccumulatePass', 'AccumulatePass', {'enabled': True, 'outputSize': 'Default', 'autoReset': True, 'precisionMode': 'Single', 'maxFrameCount': 0, 'overflowMode': 'Stop'})
    g.create_pass('FSR', 'FSR', {})
    g.create_pass('OutputSwitch', 'Switch', {'count': 5, 'selected': 4, 'i0': 'DLSS', 'i1': 'TAA', 'i2': 'Accumulate', 'i3': 'FSR', 'i4': 'RayReconstruction'})
    g.create_pass('RayReconstructionPass', 'RayReconstructionPass', {})
    g.add_edge('DitherVBuffer.vbuffer', 'VBufferLighting.vbuffer')
    g.add_edge('DitherVBuffer.mvec', 'TAA.motionVecs')
    g.add_edge('DitherVBuffer.mvec', 'DLSSPass.mvec')
    g.add_edge('DitherVBuffer.vbuffer', 'UnpackVBuffer.vbuffer')
    g.add_edge('UnpackVBuffer.posW', 'RayShadow.posW')
    g.add_edge('RayShadow.visibility', 'VBufferLighting.visibilityBuffer')
    g.add_edge('VBufferLighting.color', 'DLSSPass.color')
    g.add_edge('VBufferLighting.color', 'TAA.colorIn')
    g.add_edge('VBufferLighting.color', 'AccumulatePass.input')
    g.add_edge('VBufferLighting.color', 'FSR.color')
    g.add_edge('DitherVBuffer.mvec', 'FSR.mvec')
    g.add_edge('DLSSPass.output', 'OutputSwitch.i0')
    g.add_edge('TAA.colorOut', 'OutputSwitch.i1')
    g.add_edge('OutputSwitch.out', 'ToneMapper.src')
    g.add_edge('FSR.output', 'OutputSwitch.i3')
    g.add_edge('AccumulatePass.output', 'OutputSwitch.i2')
    g.add_edge('UnpackVBuffer.rasterZ', 'DLSSPass.depth')
    g.add_edge('UnpackVBuffer.rasterZ', 'FSR.depth')
    g.add_edge('DitherVBuffer.mvec', 'RayReconstructionPass.mvec')
    g.add_edge('VBufferLighting.color', 'RayReconstructionPass.color')
    g.add_edge('UnpackVBuffer.linearZ', 'RayReconstructionPass.linearZ')
    g.add_edge('UnpackVBuffer.roughness', 'RayReconstructionPass.roughness')
    g.add_edge('RayReconstructionPass.output', 'OutputSwitch.i4')
    g.add_edge('UnpackVBuffer.diffuse', 'RayReconstructionPass.diffAlbedo')
    g.add_edge('UnpackVBuffer.specular', 'RayReconstructionPass.specAlbedo')
    g.add_edge('UnpackVBuffer.normalW', 'RayShadow.normalW')
    g.add_edge('UnpackVBuffer.normalV', 'RayReconstructionPass.normal')
    g.mark_output('ToneMapper.dst')
    return g

Dither = render_graph_Dither()
try: m.addGraph(Dither)
except NameError: None
